<?php

namespace App\Service;

use Symfony\Contracts\HttpClient\HttpClientInterface;
use Symfony\Component\Mime\Part\DataPart;
use Symfony\Component\Mime\Part\Multipart\FormDataPart;

class YoutrustSevice
{
    public function __construct(
        private HttpClientInterface $client,
        private string $yousignApiKey,
        private string $yousignApiUrl,
        private string $appPublicUrl
    ) {}

    /**
     * @param string $pdfContent The binary content of the PDF generated by Gotenberg
     * @param string $filename The name of the PDF file (e.g., "convention.pdf")
     * @param array $requestData Array containing info for email customization (sender name, subject
     * @param array $signersData Array containing info for Student, Org, and Director
     */
    public function initiateSignatureProcess(string $pdfContent, string $filename, array $requestData, array $signersData): string
    {
        // 1. Create the Signature Request
        $requestId = $this->createSignatureRequest($filename, $requestData['sender_name'], $requestData['request_subject'], $requestData['request_body']);

        // 2. Add Document to Request
        $this->addDocumentToRequest($requestId, $pdfContent, $filename);

        // 4. Add Signers (Student=s1, Org=s2, Director=s3)
        // Ensure the order matches the anchors in your PDF template
        $this->addSigner($requestId, $signersData['student'], 's1');
        $this->addSigner($requestId, $signersData['organisation'], 's2', 2);
        $this->addSigner($requestId, $signersData['director'], 's3', 3);

        // 5. Activate Request (Sends emails)
        $this->activateRequest($requestId);

        return $requestId;
    }

    private function addDocumentToRequest(string $requestId, string $content, string $filename): void
    {
        $formData = new FormDataPart([
            'file' => new DataPart($content, $filename, 'application/pdf'),
            'nature' => 'signable_document',
            'parse_anchors' => 'true' // IMPORTANT: Tells Yousign to look for {{s1...}}
        ]);

        $response = $this->request('POST', sprintf('/signature_requests/%s/documents', $requestId), [
            'headers' => $formData->getPreparedHeaders()->toArray(),
            'body' => $formData->bodyToIterable(),
        ]);
    }

    private function createSignatureRequest(string $name, ?string $senderName = null, ?string $requestSubject = null, ?string $requestBody = null): string
    {
        $response = $this->request('POST', '/signature_requests', [
            'json' => [
                'name' => $name,
                'delivery_mode' => 'email',
                'timezone' => 'Europe/Paris',
                'reminder_settings' => [
                        'interval_in_days' => 2, // Days after which to send a reminder
                        'max_occurences' => 3 // Max number of reminders
                    ],
                'email_notification' => [
                    'sender' => [
                        'type' => 'custom',
                        'custom_name' => $senderName,
                        'custom_text' => [
                            'request_subject' => $requestSubject,
                            'request_body' => $requestBody,
                        ]
                    ]
                ],
                'signers_allowed_to_decline' => false,
                'source' => 'app',
            ]
        ]);

        return $response['id'];
    }

    private function addSigner(string $requestId, array $info): void
    {
        $this->request('POST', sprintf('/signature_requests/%s/signers', $requestId), [
            'json' => [
                'info' => [
                    'first_name' => $info['firstname'],
                    'last_name' => $info['lastname'],
                    'email' => $info['email'],
                    'phone_number' => $info['phone'],
                    'locale' => 'fr'
                ],
                'signature_level' => 'electronic_signature',
                'signature_authentication_mode' => 'otp_sms', // SMS code required
            ]
        ]);
    }

    private function activateRequest(string $requestId): void
    {
        $this->request('POST', sprintf('/signature_requests/%s/activate', $requestId));
    }

    public function downloadSignedPdf(string $requestId): string
    {
        // 1. Get documents for the request
        $data = $this->request('GET', sprintf('/signature_requests/%s/documents', $requestId));

        // Assuming there is only 1 document. ID changes after signing.
        $documentId = $data[0]['id'];

        // 2. Download binary
        $response = $this->client->request('GET', sprintf('%s/documents/%s/download', $this->yousignApiUrl, $documentId), [
            'auth_bearer' => $this->yousignApiKey,
        ]);

        if ($response->getStatusCode() !== 200) {
            throw new \RuntimeException('Error downloading PDF');
        }

        return $response->getContent();
    }

    private function request(string $method, string $uri, array $options = []): array
    {
        $options = array_merge($options, [
            'auth_bearer' => $this->yousignApiKey,
        ]);

        $response = $this->client->request($method, $this->yousignApiUrl . $uri, $options);

        if ($response->getStatusCode() >= 400) {
            throw new \RuntimeException('Yousign API Error: ' . $response->getContent(false));
        }

        return $response->toArray();
    }

    private function formatPhoneNumber(string $phone): string
    {
        // Basic formatting: ensure it starts with +33 and remove spaces/dots
        // Ideally use libphonenumber for robust validation
        $phone = preg_replace('/[^0-9+]/', '', $phone);
        if (str_starts_with($phone, '0')) {
            $phone = '+33' . substr($phone, 1);
        }
        return $phone;
    }
}
