name: deploy-conventio-dev.yml
on:
    push:
        branches:
            - main
jobs:
    deploy-conventio-dev:
        runs-on: [self-hosted]
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: update code
              run: |
                  cd /var/www/conventio
                  git reset --hard
                  git pull
                  composer install
                  php bin/console doctrine:migrations:migrate --no-interaction
                  php bin/console importmap:update
                  php bin/console asset-map:compile
                  sudo chown -R www-data:www-data /var/www/conventio
                  sudo chmod 2775 /var/www/conventio && find /var/www/conventio -type d -exec sudo chmod 2775 {} \;
                  find /var/www/conventio -type f -exec sudo chmod 0664 {} \;
